export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='navyblue'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='navyblue'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='navajowhite3'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='navajowhite3'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='grey35'
POWERLEVEL9K_DIR_ETC_BACKGROUND='grey35'
POWERLEVEL9K_DIR_HOME_BACKGROUND='mediumpurple3'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='deeppink4'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='180'

ENABLE_CORRECTION="true"

plugins=(screen catimg)

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
